package generator

import (
	"fmt"
	"strings"

	"github.com/purewrt/purewrt/internal/config"
)

// EasytierConfig renders the easytier-core TOML for this router's overlay
// membership. nil when the mesh is inactive — the caller treats nil as
// "output not managed" the same way FirewallRules does.
func EasytierConfig(c config.Config) []byte {
	if !c.MeshActive() {
		return nil
	}
	m := c.Mesh
	// Hand-built configs (tests, API callers) may skip the UCI parse that
	// seeds defaults — fall back to DefaultMesh for the plumbing fields.
	d := config.DefaultMesh()
	if m.RPCPortal == "" {
		m.RPCPortal = d.RPCPortal
	}
	if m.DeviceName == "" {
		m.DeviceName = d.DeviceName
	}
	if len(m.CommunityPeers) == 0 {
		m.CommunityPeers = d.CommunityPeers
	}
	if m.ListenPort <= 0 {
		m.ListenPort = d.ListenPort
	}
	if m.APIMeshPort <= 0 {
		m.APIMeshPort = d.APIMeshPort
	}
	var b strings.Builder
	b.WriteString("# Generated by purewrt — do not edit; regenerated on apply.\n")
	b.WriteString("instance_name = \"purewrt\"\n")
	// Overlay hostname is the hwid — the machine identity, stable across
	// display renames. node_name stays a cosmetic label in UCI/LuCI only.
	fmt.Fprintf(&b, "hostname = %q\n", m.HWID)
	// machine_id pinned to the same hwid: easytier keys "config recovery
	// after disconnection" on it, which makes the DHCP allocator hand the
	// SAME overlay IP back across daemon restarts — without the pin every
	// restart could renegotiate a fresh IP, staleing persisted peer records
	// until the next mesh-sync.
	fmt.Fprintf(&b, "machine_id = %q\n", m.HWID)
	b.WriteString("dhcp = true\n")
	// Fixed listener ports: friends punch/relay to these. Kept off the UCI
	// surface until someone actually needs to change them.
	b.WriteString("listeners = [\"tcp://0.0.0.0:11010\", \"udp://0.0.0.0:11010\"]\n")
	fmt.Fprintf(&b, "rpc_portal = %q\n", m.RPCPortal)
	// Overlay port ACL, defense-in-depth UNDER the fw4 purewrt_mesh zone
	// (which stays the primary gate: its input/forward REJECT protects all
	// 0.0.0.0-bound services and blocks overlay↔LAN transit — a port
	// whitelist can't express that). Only the mesh listener and the mesh
	// API are reachable over the overlay even if zoning ever regresses.
	fmt.Fprintf(&b, "tcp_whitelist = [\"%d\", \"%d\"]\n", m.ListenPort, m.APIMeshPort)
	fmt.Fprintf(&b, "udp_whitelist = [\"%d\"]\n", m.ListenPort)
	b.WriteString("\n[network_identity]\n")
	fmt.Fprintf(&b, "network_name = %q\n", m.NetworkName)
	fmt.Fprintf(&b, "network_secret = %q\n", m.NetworkSecret)
	// community_peer (this node's rendezvous, UCI-editable) + extra_peer
	// (group-wide custom rendezvous carried in the sync-code TLVs).
	peers := append(append([]string{}, m.CommunityPeers...), m.ExtraPeers...)
	for _, p := range peers {
		p = strings.TrimSpace(p)
		if p == "" {
			continue
		}
		b.WriteString("\n[[peer]]\n")
		fmt.Fprintf(&b, "uri = %q\n", p)
	}
	b.WriteString("\n[flags]\n")
	fmt.Fprintf(&b, "dev_name = %q\n", m.DeviceName)
	// KCP proxy stays OFF: on easytier 2.6.4 the smoltcp TCP hijack it
	// enables RSTs every TCP stream entering the TUN (observed live on both
	// arm64 and x86_64 routers — SYN answered by a locally-generated RST in
	// <1 ms), which kills the ss exit and the mesh API. Plain TCP over the
	// punched UDP path works; revisit if upstream fixes the hijack.
	b.WriteString("enable_kcp_proxy = false\n")
	// Log config deliberately absent from the TOML: easytier 2.6.4 ignores
	// logger sections here (verified live — no file appears). The init
	// script drives console level via ET_CONSOLE_LOG_LEVEL: error by
	// default (both the INFO and WARN streams are unfilterable retry-loop
	// spam that cycles the syslog ring buffer, and the info banner echoes
	// network_secret), info when purewrt's log_level=debug opts a
	// debugging session in.
	return []byte(b.String())
}
