package generator

import (
	"fmt"
	"strings"

	"github.com/purewrt/purewrt/internal/config"
)

// defaultCommunityPeers are the public easytier rendezvous nodes used for
// hole-punching and relay when the sync-code carries no custom peers. Custom
// peers from the sync-code TLVs (Mesh.ExtraPeers) are appended, so a group
// can run entirely on its own infrastructure by embedding peers in the code.
var defaultCommunityPeers = []string{
	"tcp://public.easytier.top:11010",
}

// EasytierConfig renders the easytier-core TOML for this router's overlay
// membership. nil when the mesh is inactive — the caller treats nil as
// "output not managed" the same way FirewallRules does.
func EasytierConfig(c config.Config) []byte {
	if !c.MeshActive() {
		return nil
	}
	m := c.Mesh
	// Hand-built configs (tests, API callers) may skip the UCI parse that
	// seeds defaults — fall back to DefaultMesh for the plumbing fields.
	d := config.DefaultMesh()
	if m.RPCPortal == "" {
		m.RPCPortal = d.RPCPortal
	}
	if m.DeviceName == "" {
		m.DeviceName = d.DeviceName
	}
	var b strings.Builder
	b.WriteString("# Generated by purewrt — do not edit; regenerated on apply.\n")
	b.WriteString("instance_name = \"purewrt\"\n")
	fmt.Fprintf(&b, "hostname = %q\n", m.NodeName)
	b.WriteString("dhcp = true\n")
	// Fixed listener ports: friends punch/relay to these. Kept off the UCI
	// surface until someone actually needs to change them.
	b.WriteString("listeners = [\"tcp://0.0.0.0:11010\", \"udp://0.0.0.0:11010\"]\n")
	fmt.Fprintf(&b, "rpc_portal = %q\n", m.RPCPortal)
	b.WriteString("\n[network_identity]\n")
	fmt.Fprintf(&b, "network_name = %q\n", m.NetworkName)
	fmt.Fprintf(&b, "network_secret = %q\n", m.NetworkSecret)
	peers := append(append([]string{}, defaultCommunityPeers...), m.ExtraPeers...)
	for _, p := range peers {
		p = strings.TrimSpace(p)
		if p == "" {
			continue
		}
		b.WriteString("\n[[peer]]\n")
		fmt.Fprintf(&b, "uri = %q\n", p)
	}
	b.WriteString("\n[flags]\n")
	fmt.Fprintf(&b, "dev_name = %q\n", m.DeviceName)
	// KCP proxy stays OFF: on easytier 2.6.4 the smoltcp TCP hijack it
	// enables RSTs every TCP stream entering the TUN (observed live on both
	// arm64 and x86_64 routers — SYN answered by a locally-generated RST in
	// <1 ms), which kills the ss exit and the mesh API. Plain TCP over the
	// punched UDP path works; revisit if upstream fixes the hijack.
	b.WriteString("enable_kcp_proxy = false\n")
	return []byte(b.String())
}
