package generator

import (
	"fmt"
	"strings"

	"github.com/purewrt/purewrt/internal/config"
)

// defaultCommunityPeers are the rendezvous nodes used for hole-punching and
// relay when the sync-code carries no custom peers. Custom peers from the
// sync-code TLVs (Mesh.ExtraPeers) are appended, so a group can run entirely
// on its own infrastructure by embedding peers in the code.
//
// The purewrt-operated shared node replaces upstream's public.easytier.top:
// that hostname CNAMEs into .cn and NXDOMAINs under RU DNS — dead in exactly
// the censored environments this feature targets (verified live 2026-07-12).
// The shared node runs easytier-core 2.6.4 with --no-tun
// --relay-network-whitelist --relay-all-peer-rpc; NAT punch through it was
// verified live between two CGNAT-free but firewalled RU routers.
//
// Order is preference: the wss entry is tried first. It rides the shared
// node's nginx front on real 443 (SNI-routed to a localhost easytier ws
// listener via a WebSocket-proxy location) so rendezvous traffic is
// indistinguishable from ordinary HTTPS — the DPI-resistant path.
//
// pwmesh.glants.xyz is a DEDICATED A record → the rendezvous node(s) only,
// NOT the round-robin fleet behind privatebing.glants.xyz (only nodes with
// the /pwmesh nginx location + ws listener can serve wss). easytier does not
// validate the wss TLS cert (overlay auth is the network_secret), so the
// node's existing privatebing SAN cert is fine — no cert per subdomain.
// The plain tcp:11010 entry (IP-pinned) stays as a fallback for networks
// where 11010 is open but the wss front is unreachable.
var defaultCommunityPeers = []string{
	"wss://pwmesh.glants.xyz/pwmesh",
	"tcp://150.241.85.145:11010",
}

// EasytierConfig renders the easytier-core TOML for this router's overlay
// membership. nil when the mesh is inactive — the caller treats nil as
// "output not managed" the same way FirewallRules does.
func EasytierConfig(c config.Config) []byte {
	if !c.MeshActive() {
		return nil
	}
	m := c.Mesh
	// Hand-built configs (tests, API callers) may skip the UCI parse that
	// seeds defaults — fall back to DefaultMesh for the plumbing fields.
	d := config.DefaultMesh()
	if m.RPCPortal == "" {
		m.RPCPortal = d.RPCPortal
	}
	if m.DeviceName == "" {
		m.DeviceName = d.DeviceName
	}
	var b strings.Builder
	b.WriteString("# Generated by purewrt — do not edit; regenerated on apply.\n")
	b.WriteString("instance_name = \"purewrt\"\n")
	fmt.Fprintf(&b, "hostname = %q\n", m.NodeName)
	b.WriteString("dhcp = true\n")
	// Fixed listener ports: friends punch/relay to these. Kept off the UCI
	// surface until someone actually needs to change them.
	b.WriteString("listeners = [\"tcp://0.0.0.0:11010\", \"udp://0.0.0.0:11010\"]\n")
	fmt.Fprintf(&b, "rpc_portal = %q\n", m.RPCPortal)
	b.WriteString("\n[network_identity]\n")
	fmt.Fprintf(&b, "network_name = %q\n", m.NetworkName)
	fmt.Fprintf(&b, "network_secret = %q\n", m.NetworkSecret)
	peers := append(append([]string{}, defaultCommunityPeers...), m.ExtraPeers...)
	for _, p := range peers {
		p = strings.TrimSpace(p)
		if p == "" {
			continue
		}
		b.WriteString("\n[[peer]]\n")
		fmt.Fprintf(&b, "uri = %q\n", p)
	}
	b.WriteString("\n[flags]\n")
	fmt.Fprintf(&b, "dev_name = %q\n", m.DeviceName)
	// KCP proxy stays OFF: on easytier 2.6.4 the smoltcp TCP hijack it
	// enables RSTs every TCP stream entering the TUN (observed live on both
	// arm64 and x86_64 routers — SYN answered by a locally-generated RST in
	// <1 ms), which kills the ss exit and the mesh API. Plain TCP over the
	// punched UDP path works; revisit if upstream fixes the hijack.
	b.WriteString("enable_kcp_proxy = false\n")
	return []byte(b.String())
}
